# Generated by Django 4.0.3 on 2022-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_room_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='placed_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
